### ISSUE TITLE
能不能公开下logo的源代码呀

### ISSUE THREAD

**Issue by Decade-rider** [GUET-TeX-Users-Group/GUET_Beamer#1]
大佬好，我是别的学院的，商院的，想画一个自己学院的logo，希望能参考下您的代码

**Comment by YanMing-lxb** [comment]
学校 logo 是网上找的图片，这个没有源码之说

**Comment by Decade-rider** [comment]
好的，谢谢呀



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月9日(周二) 下午4:52
收件人: ***@***.***&gt;;
抄送: "Chonglin ***@***.******@***.***&gt;;
主题: Re: [YanMing-lxb/GUET_Beamer] 能不能公开下logo的源代码呀 (Issue #1)




 
学校 logo 是网上找的图片，这个没有源码之说

**Comment by YanMing-lxb** [comment]
这只能说，去网上找找了，如果没有就只能自己做一个了

**Comment by Decade-rider** [comment]
嗯嗯，好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月9日(周二) 下午4:56
收件人: ***@***.***&gt;;
抄送: "Chonglin ***@***.******@***.***&gt;;
主题: Re: [YanMing-lxb/GUET_Beamer] 能不能公开下logo的源代码呀 (Issue #1)




 
这只能说，去网上找找了，如果没有就只能自己做一个了
